version: '3.8'

services:
  webss:
    build: .
    container_name: webss-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - BROWSER_HEADLESS=true
      - MAX_CONCURRENT_BROWSERS=3
      - RATE_LIMIT_REQUESTS=50
      - RATE_LIMIT_PERIOD=60
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: webss-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
