name: Make Package Public

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  make-public:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
      
    steps:
    - name: Make package public
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
        
        echo "Making package $REPO_NAME public..."
        
        # Try to make the package public
        curl -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/user/packages/container/$REPO_NAME" \
          -d '{"visibility":"public"}' || echo "Failed to make package public via API, it might already be public or require manual action"
